spin_manifest_version = "1"
authors = ["rainsound.ai <hello@rainsound.ai>"]
description = ""
name = "rainsound-ai"
trigger = { type = "http", base = "/" }
version = "1.0"

[[component]]
id = "invoke_serverless_functions"
source = "target/wasm32-wasi/debug/serverless_functions.wasm"
allowed_http_hosts = []
# This makes assets available server-side in our serverless functions.
files = [{ source = "assets/built", destination = "/assets/built" }]
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --release --target wasm32-wasi"
watch = [
    "serverless_functions/**/*.rs",
    "serverless_functions/**/*.html",
    "serverless_functions/**/*.css",
    "assets/**/*.rs",
    "assets/**/*.html",
    "assets/**/*.css",
    "browser/**/*.rs",
    "browser/**/*.html",
    "browser/**/*.css",
    "shared/**/*.rs",
    "shared/**/*.html",
    "shared/**/*.css",
    "Cargo.toml",
]

[[component]]
id = "serve_built_assets"
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "assets/built", destination = "/" }]
# environment = { CACHE_CONTROl = "no-cache" }
[component.trigger]
route = "/built-assets/..."
# [component.build]
# command = ""
# watch = ["assets/built/**/*"]
