spin_manifest_version = "1"
authors = ["Luca Aurelia <mail@photon.garden>"]
description = ""
name = "creative_computing_website"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "serverless_functions"
source = "target/wasm32-wasi/release/serverless_functions.wasm"
allowed_http_hosts = []
files = [
    # If you change this, you should also change it in new_assets/paths.rs.
    { source = "built_assets", destination = "/built_assets" },
]
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
watch = [
    "serverless_functions/**/*.rs",
    "serverless_functions/**/*.html",
    "serverless_functions/**/*.css",
    "new_assets/**/*.rs",
    "new_assets/**/*.html",
    "new_assets/**/*.css",
    "browser/**/*.rs",
    "browser/**/*.html",
    "browser/**/*.css",
    "shared/**/*.rs",
    "shared/**/*.html",
    "shared/**/*.css",
    "Cargo.toml",
]

[[component]]
id = "built_assets"
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "built_assets", destination = "/" }]
[component.trigger]
route = "/built-assets/..."
