[package]
name = "build_images_runtime"
version = "0.1.0"
edition = "2021"
description = ""
license = "unlicensed"
repository = "https://github.com/hyperbloom-ai/creative-computing-website/"

[dependencies]
log = "0.4.20"
proc-macro2 = "1.0.69"
quote = "1.0.33"
