[package]
name = "assets"
version = "0.1.0"
edition = "2021"
description = "Assets processing."
license = "unlicensed"
repository = "https://github.com/hyperbloom-ai/creative-computing-website/"

[dependencies]
assets_runtime = { path = "../mod_runtime" }
assets_macro = { path = "../mod_macro" }
