name = "creative_computing_website_serverless_functions"
main = "build/worker/shim.mjs"
compatibility_date = "2023-09-04"

[build]
# command = "cargo install -q worker-build && worker-build --release"
command = "cargo build --release"
